### ISSUE TITLE
Webhook controller should return HTTP 200 if shop not found

### ISSUE THREAD

**Issue by msmithstubbs** [ericdude4/shopifex#38]
When a webhook is received from Shopify for an unknown shop the application should return HTTP status `200`. 

There is some code in `ShopifexWeb.WebhookController` to do this:

https://github.com/ericdude4/shopifex/blob/d3df07af0323944c9897f0a3861279da098f80c9/lib/shopifex_web/controllers/webhook_controller.ex#L48-L55

However the `nil` case will never execute because the `ShopifyWebhook` plug returns a `404` and halts the request pipeline:

https://github.com/ericdude4/shopifex/blob/d3df07af0323944c9897f0a3861279da098f80c9/lib/shopifex/plug/shopify_webhook.ex#L24-L32

I suggest the `ShopifyWebhook` should validate the request HMAC only and not create a session with the shop. If the shop does not exist it can be handled by the webhook controller.

Would you agree, and be interested in a PR to implement this?

**Comment by ericdude4** [comment]
Hey @msmithstubbs, nice find!

I like your solution but let's discuss this a little more. We should definitely address the unreachable code issue here, but I'm wondering why we would want the `ShopifyWebhook` plug to not halt the conn if the store doesn't exist?

It would be amazing if you could put together a PR for this

**Comment by msmithstubbs** [comment]
Thanks for the quick reply, @ericdude4 

> I'm wondering why we would want the ShopifyWebhook plug to not halt the conn if the store doesn't exist?

That's a really good question. A 404 would be technically correct per the HTTP spec, since the resource is not found.

The reason to return a `200` in this situation is so that Shopify doesn't retry the webhook. From the [Shopify docs](https://shopify.dev/apps/webhooks/troubleshooting#responses-and-retries):

> If your webhook didn't respond with a 200 series status code, then the delivery failed. If the delivery fails, then it's retried up to 19 times.

If we get a webhook for a shop that doesn't exist in the app database for some reason (perhaps they just uninstalled and the webhook delivery was delayed) and return a 404 Shopify will keep retrying the webhook and causing unnecessary work. 

If we return a `200` Shopify will consider delivery successful and won't retry the webhook.

Let me know what you think?

**Comment by ericdude4** [comment]
Hi @msmithstubbs yes I suspect that's what I intended when I wrote [shopifex/lib/shopifex_web/controllers/webhook_controller.ex](https://github.com/ericdude4/shopifex/blob/d3df07af0323944c9897f0a3861279da098f80c9/lib/shopifex_web/controllers/webhook_controller.ex#L48-L55). 

Are you running into an error as a result of this? I believe Shopify's system will stop retrying webhook requests after an app is uninstalled from a store - and that is the only thing which would cause a 404 to be returned here anyways. Say I accidentally deleted a store row from my table, would I rather have get some emails from Shopify letting me know my webhook is failing in order to investigate it further? A 200-level message might hide the problem from me? What do you think?

Do you have some use case which requires this change? Perhaps that will add some context.

I agree this piece of code isn't well organized - I'd just like to think it through before making any changes.

**Comment by msmithstubbs** [comment]
The scenario where shop uninstalls but a webhook is still delayed is a little contrived and unlikely to happen.
I haven't run into errors and only came across this when I was writing some tests.

It's trivial enough to swap out `Plug.ShopifyWebhook` with my own so I'll close this issue.

Great package, really good to work with! 🙏

**Comment by ericdude4** [comment]
@msmithstubbs 
Alright! Well if you have a way which this webhook plug can check all the boxes, please open a PR :) Just don't want it to fail silently when Shopify sends webhooks for a store which doesn't exist in the application database.

Thanks :) I really enjoy this library for my personal projects too. Feel free to give it star number 50!
